---
kind: "Service"
apiVersion: "v1"
metadata:
  annotations:
    ## These annontations mark the service as monitorable by Prometheus, both directly as a service level metric and
    ## via the blackbox exporter. For more information, see
    ## values.yaml
    prometheus.io/scrape: {{ .Values.monitoring.service.scrape | quote }}
    prometheus.io/probe: {{ .Values.monitoring.service.probe | quote }}
    prometheus.io/path: {{ .Values.monitoring.service.path | quote }}
    prometheus.io/port: {{ .Values.monitoring.service.port | quote }}
    ##  
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{ end }}
  labels:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{ end }}
  name: {{ template "dockermailserver.fullname" . }}
spec:
  ## If a load balancer is being used, ensure that the newer type of LB that passes along IP information is used
  ## rather than the legacy one.
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  selector:
    app.kubernetes.io/name: {{ template "dockermailserver.fullname" . }}
    release: "{{ .Release.Name }}"
  ports:
    - name: smtp
      port: 25
      targetPort: smtp
      {{- if eq .Values.service.type "NodePort" }}    
      nodePort: {{ default "30025" .Values.service.nodePort.smtp }}
      {{- end }}

    - name: submissions
      targetPort: submissions
      port: 465
      {{- if eq .Values.service.type "NodePort" }}    
      nodePort: {{ default "30465" .Values.service.nodePort.smtps }}
      {{- end }}    
    - name: submission
      targetPort: submission
      port: 587
      {{- if eq .Values.service.type "NodePort" }}    
      nodePort: {{ default "30587" .Values.service.nodePort.submission }}
      {{ end }}
  {{- if .Values.proxyProtocol.enabled }}
    - name: smtp-proxy
      targetPort: smtp-proxy
      port: 12525
    - name: subs-proxy
      targetPort: subs-proxy
      port: 10465
    - name: sub-proxy
      targetPort: sub-proxy
      port: 10587
  {{- end }}   

  {{- if and (.Values.deployment.env.ENABLE_IMAP) (not .Values.deployment.env.SMTP_ONLY) }}
    - name: imap
      targetPort: imap
      port: 143
      {{- if eq .Values.service.type "NodePort" }}    
      nodePort: {{ default "30143" .Values.service.nodePort.imap }}
      {{- end }}       
    - name: imaps
      targetPort: imaps
      port: 993
      {{- if eq .Values.service.type "NodePort" }}    
      nodePort: {{ default "30993" .Values.service.nodePort.imaps }}
      {{- end }}   
    {{- if .Values.proxyProtocol.enabled }}
    - name: imap-proxy
      targetPort: imap-proxy
      port: 10143
    - name: imaps-proxy
      targetPort: imaps-proxy
      port: 10993
    {{- end }}   
  {{- end }}   

  {{- if and (.Values.deployment.env.ENABLE_POP3) (not .Values.deployment.env.SMTP_ONLY) }}
    - name: pop3
      targetPort: pop3
      port: 110
      {{- if eq .Values.service.type "NodePort" }}    
      nodePort: {{ default "30110" .Values.service.nodePort.pop3 }}
      {{- end }}   
    - name: pop3s
      targetPort: pop3s
      port: 995
      {{- if eq .Values.service.type "NodePort" }}    
      nodePort: {{ default "30995" .Values.service.nodePort.pop3s }}
      {{- end }}    
    {{- if .Values.proxyProtocol.enabled }}
    - name: pop3-proxy
      targetPort: pop3-proxy
      port: 10110
    - name: pop3s-proxy
      targetPort: pop3s-proxy
      port: 10995
    {{- end }}   
  {{- end }}   
 
    {{- if .Values.deployment.env.ENABLE_RSPAMD }}
    - name: rspamd
      targetPort: rspamd
      port: 11334  
    {{- end }}   

    {{- if and (.Values.deployment.env.ENABLE_MANAGESIEVE) (not .Values.deployment.env.SMTP_ONLY) }}
    - name: managesieve
      targetPort: managesieve
      port: 4190  
    {{- end }}   
 
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: 9154
      targetPort: 9154       
    {{- end }}

  type: {{ default "ClusterIP" .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
    {{- if .Values.service.loadBalancer.publicIp }}
  loadBalancerIP: {{ .Values.service.loadBalancer.publicIp }}
      {{- if .Values.service.loadBalancer.allowedIps }}
  loadBalancerSourceRanges:
  {{ .Values.service.loadBalancer.allowedIps | toYaml | indent 4 }}
      {{- end }}
    {{- end }}
  {{- end }}
